# Generated by Django 3.1.6 on 2021-06-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
