# Generated by Django 3.2.3 on 2021-06-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_delete_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbox',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
