# Generated by Django 3.2.3 on 2021-06-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13)),
                ('purchase_date', models.DateField()),
                ('purchase_time', models.TimeField()),
                ('lottery_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lottery_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video_Uploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_name', models.CharField(max_length=50)),
                ('uploader_phone_number', models.CharField(max_length=13)),
                ('video_url', models.FileField(upload_to='Videos')),
                ('winner_phone_number', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Lottery_app.lottery_player')),
            ],
        ),
        migrations.CreateModel(
            name='Lottery_Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Lottery_app.lottery_player')),
            ],
        ),
        migrations.AddField(
            model_name='lottery_player',
            name='lottery_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Lottery_app.lottery_type'),
        ),
    ]
