# Generated by Django 3.1.6 on 2021-06-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lottery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery_player',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lottery_type',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lottery_winner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='video_uploader',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
